export const EVENT_MANIFEST = [
  // DrupalCon
  { file: 'drupalcon-us-chicago-2026.json', label: 'DrupalCon America 2026: Chicago' },
  { file: 'drupalcon-us-atlanta-2025.json', label: 'DrupalCon America 2025: Atlanta' },
  { file: 'drupalcon-us-portland-2024.json', label: 'DrupalCon America 2024: Portland' },
  { file: 'drupalcon-us-pittsburgh-2023.json', label: 'DrupalCon America 2023: Pittsburgh' },
  { file: 'drupalcon-us-portland-2022.json', label: 'DrupalCon America 2022: Portland' },
  { file: 'drupalcon-us-los-angeles-2015.json', label: 'DrupalCon America 2015: Los Angeles' },
  { file: 'drupalcon-la-bogota-2015.json', label: 'DrupalCon Latin America 2015: Bogotá' },
  { file: 'drupalcon-us-austin-2014.json', label: 'DrupalCon America 2014: Austin' },
  { file: 'drupalcon-us-portland-2013.json', label: 'DrupalCon America 2013: Portland' },
  { file: 'drupalcon-us-denver-2012.json', label: 'DrupalCon America 2012: Denver' },
  { file: 'drupalcon-us-chicago-2011.json', label: 'DrupalCon America 2011: Chicago' },
  { file: 'drupalcon-asia-nara-2025.json', label: 'DrupalCon Asia 2025: Nara', flagImage: './img/flags/jp.svg', flagAlt: 'Japan flag' },
  { file: 'drupalcon-asia-singapore-2024.json', label: 'DrupalCon Asia 2024: Singapore', flagImage: './img/flags/sg.svg', flagAlt: 'Singapore flag' },
  { file: 'drupalcon-asia-mumbai-2016.json', label: 'DrupalCon Asia 2016: Mumbai', flagImage: './img/flags/in.svg', flagAlt: 'India flag' },
  { file: 'drupalcon-eu-vienna-2025.json', label: 'DrupalCon Europe 2025: Vienna' },
  { file: 'drupalcon-eu-barcelona-2024.json', label: 'DrupalCon Europe 2024: Barcelona' },
  { file: 'drupalcon-eu-lille-2023.json', label: 'DrupalCon Europe 2023: Lille' },
  { file: 'drupalcon-eu-prague-2022.json', label: 'DrupalCon Europe 2022: Prague' },
  { file: 'drupalcon-eu-amsterdam-2019.json', label: 'DrupalCon Europe 2019: Amsterdam' },
  // DrupalSouth
  { file: 'drupalsouth-2026-wellington.json', label: 'DrupalSouth 2026: Wellington', default: true, flagImage: './img/flags/nz.svg', flagAlt: 'New Zealand flag' },
  { file: 'drupalsouth-2025-melbourne.json', label: 'DrupalSouth 2025: Melbourne', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2024-sydney.json', label: 'DrupalSouth 2024: Sydney', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2023-wellington.json', label: 'DrupalSouth 2023: Wellington', flagImage: './img/flags/nz.svg', flagAlt: 'New Zealand flag' },
  { file: 'drupalsouth-2022-brisbane.json', label: 'DrupalSouth 2022: Brisbane', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2021-online.json', label: 'DrupalSouth Shorts 2021: Online (Drupal@20)', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalgov-2020-online.json', label: 'DrupalSouth: DrupalGov 2020: Online', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2019-hobart.json', label: 'DrupalSouth 2019: Hobart', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2018-canberra.json', label: 'DrupalSouth 2018: Canberra', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalgov-2017-canberra.json', label: 'DrupalSouth: DrupalGov 2017: Canberra', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2017-auckland.json', label: 'DrupalSouth 2017: Auckland', flagImage: './img/flags/nz.svg', flagAlt: 'New Zealand flag' },
  { file: 'drupalgov-2016-canberra.json', label: 'DrupalSouth: DrupalGov 2016: Canberra', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2016-gold-coast.json', label: 'DrupalSouth 2016: Gold Coast', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2015-melbourne.json', label: 'DrupalSouth 2015: Melbourne', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2014-wellington.json', label: 'DrupalSouth 2014: Wellington', flagImage: './img/flags/nz.svg', flagAlt: 'New Zealand flag' },
  { file: 'drupalcon-au-sydney-2013.json', label: 'DrupalCon Australia 2013: Sydney', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2012-melbourne.json', label: 'DrupalSouth 2012: Melbourne (Drupal Down Under)', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-2011-brisbane.json', label: 'DrupalSouth 2011: Brisbane (Drupal Down Under)', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  // DrupalSouth Community Day
  { file: 'drupalsouth-community-day-2025-canberra.json', label: 'DrupalSouth Community Day 2025: Canberra', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-community-day-2024-canberra.json', label: 'DrupalSouth Community Day 2024: Canberra', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' },
  { file: 'drupalsouth-community-day-2023-canberra.json', label: 'DrupalSouth Community Day 2023: Canberra', flagImage: './img/flags/au.svg', flagAlt: 'Australia flag' }
];

export const ENABLED_EVENT_CATEGORIES = ['DrupalSouth', 'DrupalSouth Community Day'];
